### ISSUE TITLE
Issue Report on Docker-in-Docker Problem

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#11]
### Issue Description
When using `ghcr.io/christopherhx/gitea-actions-runner:v0.0.9` as a self-hosted runner, it has been observed that both `docker/setup-qemu-action@v2` and `docker/setup-buildx-action@main` fail to function properly with the following configuration:

```
ubuntu:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@main

```
