### ISSUE TITLE
Resolving the issue of inside_vm_job depending on action-id generated by action-up in gitea-actions-runner

### ISSUE THREAD

**Issue by erik-bershely** [ChristopherHX/gitea-actions-runner#15]
Thank you to @ChristopherHX for the dedication to developing gitea-actions-runner, which provides a great solution for integrating github-runner into Gitea. However, during usage, I encountered some issues.

Specifically, I noticed a scenario in veertuinc's anka-actions-up (https://github.com/veertuinc/anka-actions-up), where inside_vm_job's runs-on depends on a self-hosted runner, and the identification of this runner is determined by the action-id generated by the action-up job. This mechanism works fine when using github + https://github.com/actions/runner. However, when using gitea + gitea-actions-runner + https://github.com/actions/runner, it seems to encounter problems.

Specifically, I found that inside_vm_job remains blocked even though the action-up step successfully registers the runner with gitea. I suspect that inside_vm_job's runs-on cannot retrieve the action-id generated by action-up.

Below is the YAML code snippet:
```
jobs:
 
  action-up:
    runs-on: ubuntu-latest
    steps:
      - uses: veertuinc/anka-actions-up@v1
        id: action-up
        with:
          gh-pat: ${{ secrets.SERVICE_USER_PAT }}
          template-id: '9690461a-02b5-412d-8778-dab4167743db'
          controller-url: 'https://controller.mysite.com'
    outputs:
      action-id: ${{ steps.action-up.outputs.action-id }}

  inside_vm_job:
    needs: action-up
    runs-on: [ self-hosted, "${{ needs.action-up.outputs.action-id }}" ]
    steps:
      - name: Inside VM Job
        id: inside_vm_job
        run: |
          echo "running on runner inside of VM (${{ needs.action-up.outputs.action-id }})"
          echo "user: $USER"
          echo "home: $HOME"
          
  action_down:
    if: always()
    needs: [ action-up, inside_vm_job ]
    runs-on: ubuntu-latest
    steps:
      - uses: veertuinc/anka-actions-down@v1
        with:
          action-id: ${{ needs.action-up.outputs.action-id }}
          gh-pat: ${{ secrets.SERVICE_USER_PAT }}
          controller-url: 'https://controller.mysite.com'
```

Therefore, I kindly invite @ChristopherHX, the author, to improve gitea-actions-runner to address this issue. Thank you!

**Comment by erik-bershely** [comment]
> I don't think `veertuinc/anka-actions-up` works with gitea in any way. You provide GitHub Credentials to it and it registeres the runner to Github.com not gitea. (see ghes note in readme)
> 
> Typically orchestration tools for github.com/GHES doesn't work together with this wrapper.
> 
> * they depend (those are not emulated)
>   
>   * on webhooks
>   * on github rest api
>   * actions/runner registration (a different project from me also emulates this, but then it's no longer Gitea Actions managing the workflows)
> * this tool (emulates the following)
>   
>   * wraps the undocumented lowlevel protocol of actions/runner
>   * directly executes an unregistred actions/runner (only creating a dummy .runner file)
> 
> It would be a big challenge to make generic orchestration tools for Actions work on Gitea.
> 
> Additionally Gitea Actions would need to support job outputs like `needs.action-up.outputs.action-id`.
> 
> I believe it evaluated to an empty string and would even be broken if the action would be register a runner to gitea.
> 
> See https://gitea.com/gitea/act/src/commit/15045b4fc0f33dfc6ab27b6398195d2c2e3f26ce/pkg/jobparser/jobparser.go#L34, https://docs.gitea.com/usage/actions/comparison#complex-runs-on

I removed the logic of github runner credentials and it can run normally. At present, it is the action-id problem caused by the run-on of inside_vm_job depending on action-up.

**Comment by erik-bershely** [comment]
> > I removed the logic of github runner credentials and it can run normally https://github.com/veertuinc/anka-actions-up/blob/main/src/action.ts#L102-L114. At present, it is the action-id problem caused by the run-on of inside_vm_job depending on action-up.
> 
> So you are able to see the runner with label `self-hosted,<action-id>` in Gitea Settings?
> 
> I wonder what you did to get that far.

Because inside_vm_job keeps spinning. So the instance is not destroyed.
<img width="1172" alt="1-1" src="https://github.com/ChristopherHX/gitea-actions-runner/assets/158459147/1c8a25e1-2926-4732-bab8-68a605efbe80">
1-2
<img width="1009" alt="1-2" src="https://github.com/ChristopherHX/gitea-actions-runner/assets/158459147/ba6a563c-68f5-4daa-9647-1cfd2601c453">

Since the previous action_down was not executed, gitea's runner also contains the vm instance created by the previous action-up. If I try the following configuration, it works perfectly.
```
name: Build

on:
  - push
  - pull_request

jobs:
  action-up:
    runs-on: ubuntu-latest
    steps:
      - uses: oilrich25/anka-actions-up@main
        id: action-up
        with:
          gh-pat: 'xxxx'
          gh-base-url: 'http://192.168.1.102:3000/api/v3'
          template-id: '0c91eb16-80fb-43b6-808f-a32ad0f04e93'
          controller-url: 'https://anka.controller:8090'
          template-runner-dir: '/Users/runner/gitea-actions-runner'
          controller-root-token: ${{ secrets.ROOT_TOKEN }}
          controller-https-skip-cert-verify: 'true'
    outputs:
      action-id: ${{ steps.action-up.outputs.action-id }}

  inside_vm_job:
    needs: action-up
    runs-on: [self-hosted, da72bf4d-e7d1-470e-b357-4a89c6e100b3 ]
    # runs-on: 
    steps:
      - name: Inside VM Job
        id: inside_vm_job
        run: |
          echo "running on runner inside of VM (${{ needs.action-up.outputs.action-id }})"
          echo "user: $USER"
          echo "home: $HOME"
                    
  action_down:
    if: always()
    needs: [ action-up, inside_vm_job ]
    runs-on: ubuntu-latest
    steps:
      - uses: oilrich25/anka-actions-down@main
        with:
          action-id: ${{ needs.action-up.outputs.action-id }}
          gh-pat: 'xxxx'
          controller-url: 'https://anka.controller:8090'
          controller-root-token: ${{ secrets.ROOT_TOKEN }}
```
