### ISSUE TITLE
working-directory in action.yaml does not work as expected

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#3]
### Issue Description:

I want to express my gratitude to @ChristopherHX for the ChristopherHX/gitea-actions-runner project. Thank you for your efforts. However, I've encountered an issue while using ChristopherHX/gitea-actions-runner. It seems that the working-directory in the action.yaml is not functioning correctly.

I have prepared a sample test repository to demonstrate the issue:
```
oilrich25Mac-mini action-demo % tree -a .
.
├── .gitea
│   └── workflows
│       └── build.yml
└── src
    └── shell.sh
```

The content of shell.sh is as follows:

```
#!/bin/sh
uname -a
```

And the content of build.yml is as follows:

```
name: Build

on:
   - push
   - pull_request

defaults:
   run:
     shell: bash
     working-directory: src

jobs:
  linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: ./shell.sh

```

However, when attempting to execute the shell.sh script, it fails to locate the script, resulting in an error similar to the following:

```
/Users/oilrich25/Desktop/gitea-actions-runner/actions-runner/_work/_temp/7d315da6-e547-4f93-a723-2ac79ab3a917.sh: line 1: ./get-clang.sh: No such file or directory
##[error]Process completed with exit code 1.

```

To further investigate, I created an additional script `shell2.sh` in the action-demo directory:

```
#!/bin/sh
ls
```

I modified the build.yml content as follows:

```
name: Build

on:
   - push
   - pull_request

defaults:
   run:
     shell: bash
     working-directory: src

jobs:
  linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: ./shell2.sh

```

Surprisingly, this time the execution was successful. This suggests that the working-directory: src setting is not effective as expected.

### Steps to Reproduce:

1. Create a repository structure as described above.
2. Use the provided build.yml with working-directory: src.
3. Attempt to execute a script located in the src directory.

### Expected Behavior:

The script specified in the working-directory should be located and executed successfully.

### Actual Behavior:

The script specified in the working-directory is not found, resulting in an error during execution.

### Additional Information:

- The https://github.com/actions/runner/releases version used is v2.311.0.

https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-win-x64-2.311.0.zip
https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-osx-arm64-2.311.0.tar.gz
https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-x64-2.311.0.tar.gz
