### ISSUE TITLE
Unable to Locate XDG_CACHE_HOME and GOCACHE with actions/setup-go@v3 in ChristopherHX/gitea-actions-runner

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#5]
### Issue Description:
When using ChristopherHX/gitea-actions-runner in conjunction with actions-runner/bin/Runner.Worker, there is an issue with the actions/setup-go@v3 action. Specifically, it fails to locate XDG_CACHE_HOME and GOCACHE during the execution.

### Steps to Reproduce:
Use the following configuration for `actions/setup-go@v3`:
```
##[group]Run actions/setup-go@v3
with:
  go-version: >=1.21.0
  check-latest: false
  cache: false
env:
  CACHE_EPOCH: 1
  CCACHE_MAXFILES: 0
  CCACHE_MAXSIZE: 200M
  SCCACHE_CACHE_SIZE: 200M
##[endgroup]
```
Execute the workflow with the specified configuration.

### Expected Behavior:

The actions/setup-go@v3 action should successfully set up Go version >=1.21.0 without encountering issues related to the missing XDG_CACHE_HOME and GOCACHE.

### Actual Behavior:

The action encounters the following error:
```
warning: GOPATH set to GOROOT () has no effect
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
##[error]Command failed: /root/oilrich25/gitea-actions-runner/actions-runner/_work/_tool/go/1.21.3/x64/bin/go env\nwarning: GOPATH set to GOROOT () has no effect\nbuild cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined\n
```

### Additional Information:

1. Operating System: Linux
2. Go Version: 1.21.3
3. Runner Environment: `ChristopherHX/gitea-actions-runner` with `actions-runner/bin/Runner.Worker`

### Notes:

This issue seems to be related to the inability to locate the necessary build cache due to the absence of definitions for GOCACHE, XDG_CACHE_HOME, and HOME. Investigating and resolving this issue would ensure the successful execution of the workflow.

**Comment by oilrich25** [comment]
Currently I have to set GOCACHE, XDC_CACHE_HOME in `action.yaml`. However, it seems that there is no need to set it in `nektos/act`. The values ​​​​of GOCACHE and XDC_CACHE_HOME are filled in by default. There is no need to set GOCACHE and XDC_CACHE_HOME in `action.yaml`.

```
name: Build

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash
    working-directory: image
env:
  CACHE_EPOCH: 1
  CCACHE_MAXSIZE: 200M
  CCACHE_MAXFILES: 0
  SCCACHE_CACHE_SIZE: 200M
  GOCACHE: /root/gocache
  XDC_CACHE_HOME: /root/gocache
```
