### ISSUE TITLE
Authorization Error when using sigyl-actions/gitea-action-release-asset with ChristopherHX/gitea-actions-runner Description

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#6]
I have recently switched from using `https://gitea.com/gitea/act_runner` to `ChristopherHX/gitea-actions-runner` for my Gitea Actions workflow. Previously, the workflow with `https://gitea.com/gitea/act_runner` and `sigyl-actions/gitea-action-release-asset` worked seamlessly, allowing successful compilation and release asset uploads. However, after the switch(` ChristopherHX/gitea-actions-runner`), I encountered authorization issues with the same `sigyl-actions/gitea-action-release-asset`.

**Note: `sigyl-actions/gitea-action-release-asset` is a node project**

### Steps to Reproduce

Use the following action.yaml configuration with https://gitea.com/gitea/act_runner (successfully runs):
```
name: Build

on:
  push:
    branches: [master]
    paths-ignore: [README.md]
  release:
    types: [published]

defaults:
  run:
    shell: bash
env:
  CACHE_EPOCH: 1
  CCACHE_MAXSIZE: 200M
  CCACHE_MAXFILES: 0
  SCCACHE_CACHE_SIZE: 200M
  GOCACHE: /root/gocache
  XDC_CACHE_HOME: /root/gocache
jobs:
  ubuntu-20:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: create gitea release
        uses: sigyl-actions/gitea-action-release-asset@main
        if: ${{ github.event_name == 'release' }}
        with:
          asset: Dockerfile
          asset-name: Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
```

Switch to ChristopherHX/gitea-actions-runner and use the same action.yaml (fails with Unauthorized error).

### Expected Behavior

I expect the sigyl-actions/gitea-action-release-asset to run successfully with ChristopherHX/gitea-actions-runner as it did with https://gitea.com/gitea/act_runner.

### Actual Behavior

The workflow fails with the following error:
```
##[error]Unauthorized
```
