### ISSUE TITLE
Bug Report for ${{ github.job }} in GitHub Actions Configuration

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/gitea-actions-runner#7]
### Issue Description

In the current GitHub Actions configuration, there is an issue with the ChristopherHX/gitea-actions-runner where the expected output of ${{ github.job }} is 'android', but the actual output does not match this expectation.

### Relevant Configuration
```
name: Build

on:
   - push
   - pull_request

defaults:
  run:
    shell: bash
    working-directory: src
env:
  CACHE_EPOCH: 1
  CCACHE_MAXSIZE: 200M
  CCACHE_MAXFILES: 0
  SCCACHE_CACHE_SIZE: 200M
  GOCACHE: /root/gocache
  XDC_CACHE_HOME: /root/gocache
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.job }}
```

### Actual Behavior

The actual output of `${{ github.job }}` does not match the expected value `android`.
`using ChristopherHX/gitea-actions-runner in conjunction with actions-runner/bin/Runner.Worker`
<img width="754" alt="bug1" src="https://github.com/ChristopherHX/gitea-actions-runner/assets/152663740/ffc57784-c544-456c-8e7d-4b5ede513d06">

### Expected Behavior

Expect `${{ github.job }}` to output `android` as specified in the configuration.
`https://gitea.com/gitea/act_runner`
<img width="756" alt="ok1" src="https://github.com/ChristopherHX/gitea-actions-runner/assets/152663740/2dfa2bd6-662e-408c-8704-893e65c7c10d">
