### ISSUE TITLE
Request for Docker-in-Docker Support in ChristopherHX/gitea-actions-runner

### ISSUE THREAD

**Issue by vitalyk-ultinarity** [ChristopherHX/gitea-actions-runner#9]
Thank you to @ChristopherHX for providing the `ChristopherHX/gitea-actions-runner` project, enabling its integration with action/runner.server, which has been immensely beneficial for our project.

While `https://gitea.com/gitea/act_runner` already implements `Docker-in-Docker` support, I prefer using `action/runner.server`. Unfortunately, the current version of `ChristopherHX/gitea-actions-runner` does not support `Docker-in-Docker`, preventing deployment on `Kubernetes` or `Docker`.

To enable `Docker-in-Docker` support for `ChristopherHX/gitea-actions-runner`, it is necessary to package `action/runner.server` into the container. I would like to inquire whether @ChristopherHX has any plans to add `Docker-in-Docker` support to the project.

Here is a partial docker-compose configuration that illustrates our usage of your runner:
```
...
gitea:
  image: gitea/gitea
  ...

runner:
  image: christopherhx/gitea-actions-runner
  restart: always
  depends_on:
    - gitea
  volumes:
    - ./data/act_runner:/data
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - GITEA_INSTANCE_URL=<instance url>
    - GITEA_RUNNER_REGISTRATION_TOKEN=<registration token>
    # Additional parameters needed for Docker-in-Docker support
...

```
